apiVersion: v1
kind: Secret
metadata:
  name: mybookslist-com-tls
type: kubernetes.io/tls
data:
  tls.crt: |
           MIIFFTCCAv2gAwIBAgIUJI0O3hq7bqLkHZn7g3JAqOlBg1IwDQYJKoZIhvcNAQEL
           BQAwGjEYMBYGA1UEAwwPbXlib29rc2xpc3QuY29tMB4XDTIyMDIwNDE1MDMxMFoX
           DTIzMDIwNDE1MDMxMFowGjEYMBYGA1UEAwwPbXlib29rc2xpc3QuY29tMIICIjAN
           BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1xtu/neQOFPe61+eTXKNEG3uwLB8
           G407iw1lIN31DUmMtHuEAb6H/LVUmFIT2E1nGxJuEl4fBO6UkMKOTmVvQwAZtIob
           xzDIQfRhxcAYKN5fPueqZ8e2RcJuYBPC0RJnvVpMbMW7XNh0Xfn/PJNJ5G87KRK0
           eu7EnlqrDTn2x5I7px4X87EIhesD7amfWJzXdqnkkkGi4Pdt9aQBpHx164KQFbRN
           qzoJSo9Pd+xjtfmIf81wBs7+KHLsRKj7I+mnUubh3X89Q7+DJLII7B6a4FmpijJY
           zFxdZWfOSAypZullkd+bbXhmXSPXIK8QdxRY/3fhoBG2KOCStpHMp1f4YleUdElz
           0jeBmbOITKfPo8ri01PBbwkHp5RRNz6cG+6q+WRx7t+o8AHiSvUvmgzT9mBQrqzK
           lahpCcxVC8e8dkGDGqSYSY95XwiMkywEf2nr9RaoG4mVl/NOMD5DLsQ/qjvFj/1+
           S5wKC462UJPtDXGc2LqwDpZ3hAB3WFoJCKyPi1dOvh5wTSsLgnFPus3L0+r7e9j8
           0Evl7bc1xwMh7saPSEtcVVy1pBiaawHki7ICAWZ9I0xESiSxKcTGkHlAGKqjKBNR
           CXJhZBszvoSNeNodIWYAN+xyg7ofypJ4qPCUoDV8skYw1CIfxois9W580cLPaxee
           0VytkH1mBjgCGp8CAwEAAaNTMFEwHQYDVR0OBBYEFMbHRHBRKSCrndcND3amJohD
           1cPKMB8GA1UdIwQYMBaAFMbHRHBRKSCrndcND3amJohD1cPKMA8GA1UdEwEB/wQF
           MAMBAf8wDQYJKoZIhvcNAQELBQADggIBADNhfjBfQRDknoZt9SUAS9oNhHhDEMW0
           Z625z09xL86d7E0hMLNIiw1Lftr/icdKyuDgBuOjboeszSxaV4VWZvqI1w5m9EgI
           fuVOrVQktzVKShML0F/tchBpcpRsfxL8+icfokPFAFKS6bqdGaWVRO4U4ruTY+1N
           4w3GpwEy6ibQFbIj9841sNyFFXDVihYEbgWmKWuNif2QxOhxZOUOlnq40czxVsqA
           6pS8DI7hYQ8KlAemjoLshTrFtksb5YDutD5n8a744wUDYrKg5iKbonykf36HfnJk
           4GSVaEI6klhKVK18GZxr+1pHpsKXUIQ+JCKxm1OYFgcL8cR+0vi7BrwrWpd1Sbs2
           vQOH491Axjp4fiSh7wjdZMTX8DRmlJxp5dhq1X9R2n5+skSMbIsqsxaAOu8ADwec
           pvk4E2bzrgaQQOoJQFPiBhM4Yul9X7YH5KqLuZQsIsnzkuRLpg7S+5PbaPTJG+Ne
           5IDO2rD9q89hCK+ONOwII1ob5IQlY7bGRZeZdwRH5swQ58mxDr84ZsqSmDy1sZa5
           rVuXQAhfZ735bRn1S+vo5xlGF6Wwn5i+8N3+Vpy+P8PTaoS+8teWLeciCWJZ+6b3
           qIpbxKtigEbZPcChCJ9yz7pWlxU6IP323E1I68U4P6hUHAW8sLJxDhzO4byccPqH
           nUKhvPcEkKAJ

  tls.key: |
           MIIJRQIBADANBgkqhkiG9w0BAQEFAASCCS8wggkrAgEAAoICAQDXG27+d5A4U97r
           X55Nco0Qbe7AsHwbjTuLDWUg3fUNSYy0e4QBvof8tVSYUhPYTWcbEm4SXh8E7pSQ
           wo5OZW9DABm0ihvHMMhB9GHFwBgo3l8+56pnx7ZFwm5gE8LREme9Wkxsxbtc2HRd
           +f88k0nkbzspErR67sSeWqsNOfbHkjunHhfzsQiF6wPtqZ9YnNd2qeSSQaLg9231
           pAGkfHXrgpAVtE2rOglKj0937GO1+Yh/zXAGzv4ocuxEqPsj6adS5uHdfz1Dv4Mk
           sgjsHprgWamKMljMXF1lZ85IDKlm6WWR35tteGZdI9cgrxB3FFj/d+GgEbYo4JK2
           kcynV/hiV5R0SXPSN4GZs4hMp8+jyuLTU8FvCQenlFE3Ppwb7qr5ZHHu36jwAeJK
           9S+aDNP2YFCurMqVqGkJzFULx7x2QYMapJhJj3lfCIyTLAR/aev1FqgbiZWX804w
           PkMuxD+qO8WP/X5LnAoLjrZQk+0NcZzYurAOlneEAHdYWgkIrI+LV06+HnBNKwuC
           cU+6zcvT6vt72PzQS+XttzXHAyHuxo9IS1xVXLWkGJprAeSLsgIBZn0jTERKJLEp
           xMaQeUAYqqMoE1EJcmFkGzO+hI142h0hZgA37HKDuh/Kknio8JSgNXyyRjDUIh/G
           iKz1bnzRws9rF57RXK2QfWYGOAIanwIDAQABAoICAQCXk5BKJixtVMR/rZhaUL8Q
           dbbI91PtAj+UA7NgTqeQXmSVBXiG1iDzNT/QOf4b7KccD4eaz9Ih4pCz1TT8D0Qw
           vVBfxPZADaL/vtpqw6sCmXgaVprgmH1beN/YOfSM6OBLMOcrusYFbc3KLxDpOYzX
           OH5CuhiNi9TnFVL1dgPsq6H3aCBOq1ArNelFvsI3agX2a09StIe26QQGFTTHGKDr
           fMxVTwFwB+xmKsg/5EZ7A8Ro8nXfhlrYW+sbksuticdLhsBgGXotVDVwVTguUn6m
           Wug6JrImB2wUuepFIQ76Irtc6GmY4T+YoFnGgTYkAyWXl31ZE0H+WgloNyM0RKwU
           LH3Dinnq0cyABPW92gaWU9sk2APcqOs5i5hXb0wC79litf9sq6qfqiRwV40WyXbE
           jQznGcKHUA73FIJCLrXM4pyqxhEv8y7k5lOKOA/HpzXoC6KaLVoVyaFGy7e9ZqO1
           lIOO0LbZigQQCPgS7ZsH6K2FmUcSiSwJhEwPBdh3XSEm/8IZgOTLXtEmtV49fMPp
           HTJXH1ABjbg6/XGSoBxpPBpSJSL2W2G1H16zJwArCdA55FTW54GlUCLRsn5GJ6KG
           KG9ONAn4iPNbft8BPVwOmYqNvFhu1FL0s6aylWossayvl2tInFIDvhOCf1WnNlSF
           /dZCfBm8m+JwfrY3g/UeKQKCAQEA/n1lUU8pEkU46xHr+Tib2FcRCsT2isPXYn00
           8iv+hxyHJnYSw9C8g9WTx+iO3vypdJj4pQ2OlPBXg4YqqufvOfoe6pvBlw1E0xXq
           aRFrcgOvEcLDbj0fRBQHqarJYXz6RLf2JIUJYKcOe3HF4gZFMkhg1yamnjN3r1si
           ptaPipjBN37EIGyNird4JyMhtv8VspBvQ9os2pTn83hifhFrccPHE2saT4wTiAUo
           sBa6UOzLqi4+O8FYAMRjJVEBOLeLLoE8YQf7IpGauRyhoKIjRc+P5KQzMiFf9WCS
           9vg0uJ4PQ8+QFVOs+/Dia7dJu2uNOG3bOLLUWFyIKbGHl1aCpQKCAQEA2GI10ltY
           Q2EN4mmUOGbyEhoX0xL2SnqijR4aGp3snLuHFUzOcwYndX11zbTyAkn4pTg5FXAt
           06YRhHm3vJ/eCr9IzEY8dMGUy2NU9s1zcUhZs2Sk2wNOrC75oLoSUkBqhvFJ+gZ6
           dDVy//y3aOllVohCQepAHeyuI1igJR3x3V9jKVuMBEQVdmf6Fsrsi4T+1ANzxPlk
           BaXr34gFNrmS6TBWgnTHSshRynOeaIN2xyWFLjoFxjL43wlJWe2ue/A1v+i+EoHA
           LB+yqj76/B1WBmbtjG8qF3meFgFo4z7xAGIDNa2OAE+vU/QjjX7YQ1SbdB94w42E
           7TeGdIpNchA48wKCAQEAlMBxD2TI6gACNAzmtGbtWTgTIwtb3GJ6q/vpjcA/Z3Q6
           XzXW5BRHjHuzhL8fe6GN3zRm6fsRo2cUkDFFEV6+i1Hy7kkakBNWble6C6398sfK
           dgQ0vWQGuYFHtVm5mj02ACLTQidtAszC/07STrpBihGaYUgbTg9hXuNTTtfNUULW
           dXyoYRdyaGmzVpUHaPKTGSupjayiWSV+quZsE6pU9ktsOqJ435RN+kyhqsOuJg0z
           QocDI2Rw7wnbtf0yTJekSAuMYl8K4PrgyGC+7Ki5G14mioubzSqK71+Cp88O6fah
           j45sdrrROvZjMnkRJPbJtfkokWyeCAQWJuC5E7GibQKCAQEA188jpNiLsC/VHDJ2
           rMYnulwh1Nd9ooyrIJmcKV3Ghg8WS+0dnmTN6AUn//Duyc+i2I25iSMn4YYoxHpt
           AQhk+U0MOwf19fC4CR3ZuIjyEVK6fAvty62BwoLbXy0VZsluNYXjZSUe7lX8i0ku
           V8kn0+T0SC9soSvUBda3ai1yc3pWOQJgJEUPLtfG+wKKZyBO039Z8GNXGbcBCCDu
           KkVtO3uFXHlB5tjhkkw7+jrbtQU7zf36klF2G2R0ruc59cx+nxdusqCL3LYEiH1l
           7xsHGD2BwGWCkoUuYP4o8TRuQxZ94wRksvTGhbHh35ZZ9NUmceuNk2PK5phRVlw1
           n4SEdwKCAQEAsqjvzEsTxLxr06+X/TUISdTxR6BoC4ZVAv4OXnwmBvjGm8927foJ
           3/cHb5LBBjzix3AQgfsmjUk1tsJjYF2apyVc6NzRHVOewVTLJIGXl/DF5qaUALoM
           Me8+zsucNXP3FaYgDGDhAme3iIF3xFHvYiy4iHfK48+arHjKMvrSw+Tm30IeZQ6P
           OlX4TV6wEq1CQXeNv3nD5C9pOE5tghLyJdIhGBDRi5u/rDPTL/+RjtoAOR8PDTfo
           E5m8nKQAkNQWyGVr4nzYs+XNCKkrm5qZQUSmoDknDA9VCAOBMjcUGOsNNBAtl6Ke
           MfqttD4l6Z4WWdfuGZDdNEVYCjTzbxYzhg==


