apiVersion: v1
kind: Service
metadata:
  name: {{ include "vu-sc-server-chart.fullname" . }}
  labels:
    {{- include "vu-sc-server-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    {{- include "vu-sc-server-chart.selectorLabels" . | nindent 4 }}
